In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits=load_digits()

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [8]:
#Logistic Regression
lr= LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9666666666666667

In [14]:
#SVM

Svm= SVC(gamma='auto')
SVm.fit(X_train, y_train)
SVm.score(X_test, y_test)

0.36944444444444446

In [29]:
#Random Forest
rf= RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test,y_test)

0.9833333333333333

In [30]:
from sklearn.model_selection import KFold 

kf= KFold(n_splits=3)
kf

KFold(n_splits=3,random_state=None,shuffle=False)
for train_index,test_index in kf.split([1,2,3,4,5,6,7]):
    print (train_index, test_index)


[3 4 5 6] [0 1 2]
[0 1 2 5 6] [3 4]
[0 1 2 3 4] [5 6]


In [33]:
def get_score(model, X_train, x_test, y_train, y_test): 
    model.fit(X_train, y_train) 
    return model.score(x_test,y_test)

In [52]:
from sklearn.model_selection import StratifiedKFold 
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = [] 
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[train_index], digits.data[test_index],digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver= "liblinear",multi_class="ovr"), X_train, X_test, y_train, y_test)) 
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train,X_test,y_train,y_test))

In [53]:
# Load the digits dataset
digits = load_digits()

In [55]:
print("Logistic Regression Scores:",scores_logistic)
print("SVM Scores:",scores_svm)
print("Random Forest Scores:",scores_rf)

Logistic Regression Scores: [0.8948247078464107, 0.9532554257095158, 0.9098497495826378]
SVM Scores: [0.3806343906510851, 0.41068447412353926, 0.5125208681135225]
Random Forest Scores: [0.9248747913188647, 0.9482470784641068, 0.9382303839732888]
