In [1]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [2]:
import numpy as np

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = np.dot(X,Y)

print(result)

[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


In [1]:
import time
import numpy as np
import concurrent.futures

def sequential_matrix_multiply(matrix_a, matrix_b):
    return np.dot(matrix_a, matrix_b)

def parallel_matrix_multiply(matrix_a, matrix_b, num_threads):
    with concurrent.futures.ThreadPoolExecutor(max_workers=num_threads) as executor:
        result = np.zeros_like(matrix_a)
        chunk_size = len(matrix_a) // num_threads
        futures = []

        for i in range(num_threads):
            start_idx = i * chunk_size
            end_idx = start_idx + chunk_size
            futures.append(executor.submit(np.dot, matrix_a[start_idx:end_idx], matrix_b, out=result[start_idx:end_idx]))

        concurrent.futures.wait(futures)

    return result

matrix_sizes = [(5, 5), (50, 50), (100, 100), (1000, 1000)]

for matrix_size in matrix_sizes:
    rows, cols = matrix_size
    matrix_a = np.random.rand(rows, cols)
    matrix_b = np.random.rand(cols, rows)

    # Sequential multiplication
    start_time = time.time()
    result_seq = sequential_matrix_multiply(matrix_a, matrix_b)
    sequential_time = time.time() - start_time

    # Parallel multiplication with different numbers of threads
    for num_threads in [2, 4, 8]:
        start_time = time.time()
        result_parallel = parallel_matrix_multiply(matrix_a, matrix_b, num_threads)
        parallel_time = time.time() - start_time

        print(f"Matrix Size: {matrix_size}, Threads: {num_threads}")
        print(f"Sequential Time: {sequential_time:.20f} seconds")
        print(f"Parallel Time: {parallel_time:.20f} seconds")
#         print(f"Sequential Time: {sequential_time} seconds")
#         print(f"Parallel Time: {parallel_time} seconds")
        print("=" * 30)

Matrix Size: (5, 5), Threads: 2
Sequential Time: 0.32923650741577148438 seconds
Parallel Time: 0.00000000000000000000 seconds
Matrix Size: (5, 5), Threads: 4
Sequential Time: 0.32923650741577148438 seconds
Parallel Time: 0.01562833786010742188 seconds
Matrix Size: (5, 5), Threads: 8
Sequential Time: 0.32923650741577148438 seconds
Parallel Time: 0.00000000000000000000 seconds
Matrix Size: (50, 50), Threads: 2
Sequential Time: 0.00000000000000000000 seconds
Parallel Time: 0.00000000000000000000 seconds
Matrix Size: (50, 50), Threads: 4
Sequential Time: 0.00000000000000000000 seconds
Parallel Time: 0.01561713218688964844 seconds
Matrix Size: (50, 50), Threads: 8
Sequential Time: 0.00000000000000000000 seconds
Parallel Time: 0.00000000000000000000 seconds
Matrix Size: (100, 100), Threads: 2
Sequential Time: 0.01562356948852539062 seconds
Parallel Time: 0.01668787002563476562 seconds
Matrix Size: (100, 100), Threads: 4
Sequential Time: 0.01562356948852539062 seconds
Parallel Time: 0.0000000