In [2]:
import numpy as np
import pandas as pd
import random 

In [7]:
w1 = np.random.rand()
w2 = np.random.rand()
b = np.random.rand()

In [9]:
i1 = np.array([1,3,5,6,8,9])
i2 = np.array([2,4,6,5,9,1])
y = np.array([1,0,0,1,0,0])

In [10]:
def nn(i1,i2,w1,w2,b):
    s = i1 * w1 + i2 * w2 + b
    return sigmoid(s)
def sigmoid(x):
    sig = (1 / 1 + np.exp(-x))
    return sig
    if sig >=0.5:
        return 1
    else: 0 

In [11]:
nn(i1,i2,w1,w2,b)

array([1.13208674, 1.01719872, 1.00223941, 1.00232439, 1.00010522,
       1.00440823])

In [12]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Randomly initialize weights and bias
w = np.random.rand(3, 1)
b = np.zeros((1, 1))

def nn(input_data):
    # Calculate the weighted sum of inputs and apply the sigmoid activation function
    s = np.dot(input_data, w) + b
    output = sigmoid(s)
    return output

# Generated input data (7 rows and 3 columns)
input_data = np.random.rand(7, 3)

# Perform a forward pass through the neural network
predictions = nn(input_data)

# Print the results
print("Generated Input Data:")
print(input_data)
print("\nNeural Network Predictions:")
print(predictions)

Generated Input Data:
[[0.1878358  0.65231807 0.82412315]
 [0.29876008 0.09567378 0.67655525]
 [0.24744777 0.48982268 0.35603491]
 [0.59040879 0.73695218 0.08636799]
 [0.38455671 0.02116937 0.07459059]
 [0.50114767 0.54106197 0.3227101 ]
 [0.51795876 0.94152941 0.59740388]]

Neural Network Predictions:
[[0.60908377]
 [0.56814554]
 [0.55951172]
 [0.54989756]
 [0.510047  ]
 [0.5605457 ]
 [0.60560181]]


In [13]:
import numpy as np
import pandas as pd

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

w = np.random.rand(2, 1)
b = np.zeros((1, 1))       

def nn(inputs):
    s = np.dot(inputs, w) + b
    out = sigmoid(s)
    return out

# Input DataFrame
data = {"x1": [1, 1, 0, 0], "x2": [1, 0, 1, 0], "y": [1, 0, 0, 0]}
df = pd.DataFrame(data)

# Extracting input values (excluding the 'y' column)
input_data = df.drop(columns=['y']).values

# Perform a forward pass through the neural network
output = nn(input_data)

print("Neural Network Output:")
print(output)

Neural Network Output:
[[0.73533256]
 [0.70566097]
 [0.53679489]
 [0.5       ]]


In [16]:
import numpy as np
import pandas as pd

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

# Randomly initialize weights and bias
w = np.random.rand(2, 1)
b = np.zeros((1, 1))       

def nn(inputs):
    s = np.dot(inputs, w) + b
    out = sigmoid(s)
    return out

def backpropagation(inputs, targets, learning_rate=0.1, epochs=1000):
    global w, b  # Declare w and b as global variables
    
    for epoch in range(epochs):
        # Forward pass
        predicted_output = nn(inputs)
        
        # Calculate the error
        error = targets - predicted_output

        # Backpropagation
        output_gradient = sigmoid_derivative(predicted_output)
        delta_output = error * output_gradient

        # Update weights
        w += learning_rate * np.dot(inputs.T, delta_output)
        b += learning_rate * np.sum(delta_output, axis=0, keepdims=True)

        # Print the error every 100 epochs
        if epoch % 100 == 0:
            print(f"Epoch {epoch}, Error: {np.mean(np.abs(error))}")

    return w, b

# Input DataFrame
d = {"x1": [1, 1, 0, 0], "x2": [1, 0, 1, 0], "y": [1, 0, 0, 0]}
df = pd.DataFrame(d)

# Extracting input and target values
input_data = df.drop(columns=['y']).values
targets = df['y'].values.reshape(-1, 1)

# Perform backpropagation
trained_w, trained_b = backpropagation(input_data, targets)

# Print the final weights and bias
print("Trained Weights:")
print(trained_w)
print("\nTrained Bias:")
print(trained_b)

Epoch 0, Error: 0.509608437989116
Epoch 100, Error: 0.32203726085085693
Epoch 200, Error: 0.27122678511359266
Epoch 300, Error: 0.2365876944579723
Epoch 400, Error: 0.21073186943841296
Epoch 500, Error: 0.19046443739990887
Epoch 600, Error: 0.1740127111534862
Epoch 700, Error: 0.16031158542117602
Epoch 800, Error: 0.1486781558896032
Epoch 900, Error: 0.13865036197235675
Trained Weights:
[[3.01187767]
 [3.0202648 ]]

Trained Bias:
[[-4.82638443]]


In [17]:
import numpy as np
import pandas as pd

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

w = np.random.rand(2, 1)
b = np.zeros((1, 1))       

def nn(inputs):
    s = np.dot(inputs, w) + b
    out = sigmoid(s)
    return out

d = {"x1": [1, 1, 0, 0], "x2": [1, 0, 1, 0], "y": [1, 0, 0, 0]}
df = pd.DataFrame(d)

input_data = df.drop(columns=['y']).values

output = nn(input_data)

output

y1= np.round(output)

In [18]:
y1

array([[1.],
       [1.],
       [1.],
       [0.]])

In [19]:
np.round(output)

array([[1.],
       [1.],
       [1.],
       [0.]])

In [20]:
y1.flatten()

array([1., 1., 1., 0.])

In [22]:
(y1.flatten() - df["y"].values)

array([0., 1., 1., 0.])

In [23]:
df["y"].values
y1

array([[1.],
       [1.],
       [1.],
       [0.]])

In [24]:
c = ((y1.flatten() - df["y"].values) ** 2) / 2

In [25]:
c

array([0. , 0.5, 0.5, 0. ])